name: bhoomi_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 11.1.0+10
# 1 this is major number;kuch badi funcitionality use hui ho to
# 0 ye hai minor number jaha kuch chhoti update di ho;
# 0 ye patch jaha kuch bugfix krne prise update krte hai
# +1 ye hia build number jahha chhoti chhoti cheeje ya bug fix krne pr ise update krna theek hoga,

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.0.9
  swipeable_button_view:
    # yaha bottomNavigation ke liye use kiya hai salomon dependency ko
  salomon_bottom_bar: ^3.3.2
  #ye page ko transestion krne ke liye
  page_transition: ^2.0.9
#  carousel_slider: ^4.0.0
  carousel_slider: ^5.0.0
  sqflite: ^2.3.3+1
  flutter_otp_text_field: ^1.1.3+2
  google_maps_flutter: ^2.1.6
#  http: ^1.2.1
#  google_fonts: ^6.2.1
#  google_fonts: ^3.0.1
#  http: ^0.13.6
  google_fonts: ^6.2.1
#  http: ^1.2.1
  http: ^1.2.2
  charts_flutter: ^0.12.0
  provider: ^6.0.0
  get: ^4.6.5
  lottie: ^3.1.2
  shared_preferences: ^2.3.1
  searchbar_animation: ^0.0.4
  flutter_sliding_up_panel: ^2.0.0
  url_launcher: ^6.1.10
  webview_flutter: ^2.0.12
  connectivity_plus: ^4.0.2
#  lottie: ^3.1.2
#  google_fonts: ^6.2.1
  flutter_inappwebview: ^6.0.0
  intl_phone_field: ^3.1.0
  image_picker: ^0.8.7+3

  path_provider: ^2.0.11
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoicon/bhoomilogo.png"
  min_sdk_android: 21
  icon_size: 80
  # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logoicon/bhoomilogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logoicon/bhoomilogo.png"
    icon_size: 48



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animation/Animation.json
    - assets/animation/networkanim.json
    - assets/logoicon/bhoomilogo.png
    - assets/icons/flag.png
    - assets/lottie/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
   - family: Schyler
     fonts:
         - asset: fonts/Schyler-Regular.ttf
         - asset: fonts/Schyler-Italic.ttf
           style: italic
   - family: Trajan Pro
     fonts:
        - asset: fonts/TrajanPro.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700

#   - family: Roboto
#     fonts:
#       - asset: assets/fonts/Roboto-Regular.ttf
#       - asset: assets/fonts/Roboto-Bold.ttf
#         style: Roboto
#         weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
